# Numpy Assignment

In [1]:
import numpy as np
heights = np.array([160, 155, 172, 165, 180, 158, 175, 163, 171, 168])

In [2]:
# Calculate the mean of the students' heights
heights_mean = heights.mean()
print(heights_mean)

# or 

heights_av = np.mean(heights)
print(heights_av)

166.7
166.7


In [3]:
# Calculate the median of the students' heights
heights_median = np.median(heights)
print(heights_median)

166.5


In [4]:
# Calculate the standard deviation of the students' heights
heights_std = np.std(heights)
print(heights_std)

7.5372408744845085


In [5]:
# Create a new array with the heights normalized, i.e.,
# each height value should be transformed to have a mean of 0 and a standard deviation of 1.

heights_normalized = (heights - heights_mean)/heights_std
print(heights_normalized)


[-0.88891945 -1.55229217  0.70317509 -0.22554673  1.76457144 -1.15426854
  1.10119872 -0.49089581  0.57050054  0.17247691]


In [6]:
print(np.mean(heights_normalized))
print(np.std(heights_normalized))

1.50712775592865e-15
0.9999999999999999


In [7]:
# Determine the shortest student in the class using NumPy's argmin function
shortest = heights.argmin()
print(shortest)

1


In [8]:
# Determine the tallest student in the class using NumPy's argmax function
tallest = heights.argmax()
print(tallest)

4


In [9]:
# Calculate the difference between the tallest and shortest students' heights.
height_range = heights.ptp() # peak_to_peak()
print(height_range)

# or

height_range1 = heights.max() - heights.min()
print(height_range1)

25
25


In [10]:
# Original array

heights = np.array([160, 155, 172, 165, 180, 158, 175, 163, 171, 168])

In [11]:
# Randomly select 5 heights from the dataset without replacement.
height_random = np.random.choice(heights, 5, replace = False)
print(height_random)

[180 155 172 168 175]


In [12]:
# Randomly select 5 heights from the dataset without replacement.
height_random = np.random.choice(heights, 5, replace = False)
print(height_random)

[160 171 168 158 172]


In [13]:
np.random.seed(659)
# Randomly select 5 heights from the dataset without replacement.
height_random = np.random.choice(heights, 5, replace = False)
print(height_random)

[180 155 171 172 158]
